---
kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: node:13.10.1
    volumes:
      - name: cache
        path: /.yarn-cache
    commands:
      - node -v
      - npm -v
      - yarn --version
      - yarn config set cache-folder /.yarn-cache
      - yarn install
      - yarn build

  - name: pubilsh
    image: plugins/docker:18.09
    volumes:
      - name: docker.sock
        path: /var/run/docker.sock
    settings:
      repo: hub.fengziyu.top/gitbook
      tags: 0.0.1
    
  - name: deployment
    image: appleboy/drone-ssh:1.5.7
    settings:
      host:
        from_secret: host
      username:
        from_secret: username
      password:
        from_secret: password   
      script:
        - cd /data/deploy
        - sh gitbook.sh
            
volumes:
  - name: docker.sock
    host:
      path: /var/run/docker.sock